/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Java.Carro;
import Java.ConfigDetalhesExteriores;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.SpinnerListModel;



public class ConfiguraDetalhesExt extends javax.swing.JFrame {

    private Carro carro;
    private String username;
    private int stock;
    private Menu_Inicial menuIni;
    private int id_configura;
    private int id_configuraExt;
   
    
   
   public ConfiguraDetalhesExt(Carro a, String username, Menu_Inicial menuIni, int id_configura) {
        initComponents();
        this.carro = a;
        this.username = username;
        this.stock=20;
        this.menuIni=menuIni;
        this.id_configura=id_configura;
        this.id_configuraExt=carro.getListaExteriores().size();
        setSpinners();
      }
   
   
   
    
    private void setSpinners() {
        SpinnerListModel tecto;
        SpinnerListModel vidros;
        SpinnerListModel parachoq;
        
        List<String> m = new ArrayList<>();
        List<String> l = new ArrayList<>();
        List<String> t = new ArrayList<>();
        t.add("tejadilho1");
        t.add("tejadilho2");
        t.add("tejadilho3");
        l.add ("duplo");
        l.add ("simples");
        m.add ("rijo");
        m.add ("bonito");
        
        
        tecto = new SpinnerListModel(t);
        jSpinnerTecto.setModel(tecto);
        
        vidros = new SpinnerListModel(l);
        jSpinnerVidros.setModel(vidros);
        
        parachoq = new SpinnerListModel(m);
        jSpinnerPara.setModel(parachoq);
    }
    
    
    public void close() {
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSpinnerTecto = new javax.swing.JSpinner();
        jSpinnerVidros = new javax.swing.JSpinner();
        jSpinnerPara = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AdicionarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("                 Exteriores");

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tecto 3€");

        jLabel3.setText("Vidros Escurecidos 3€");

        jLabel4.setText("Para choques 3€");

        AdicionarButton.setText("Adicionar");
        AdicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerVidros, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerTecto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerPara, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdicionarButton)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSpinnerTecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerVidros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addComponent(jSpinnerPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(AdicionarButton)
                .addGap(78, 78, 78)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSpinnerTecto.setModel (new javax.swing.SpinnerListModel (new String[] {""}));
        getContentPane().add(jSpinnerTecto);
        jSpinnerVidros.setModel (new javax.swing.SpinnerListModel (new String[] {""}));
        getContentPane().add(jSpinnerVidros);
        jSpinnerVidros.setModel (new javax.swing.SpinnerListModel (new String[] {""}));
        getContentPane().add(jSpinnerVidros);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void AdicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarButtonActionPerformed
        String t = (String) jSpinnerTecto.getValue();
        String l = (String) jSpinnerVidros.getValue();
        String m = (String) jSpinnerPara.getValue();
        float custo = 9;
      //  Configuração x = new Configuraçao ()
        // int ref = x.getRef();
        int ref = 20;
        //id_configuraExt = carro.getListaExteriores().size();
        
        boolean tipo = true;
      //  tipo = t.equals("Vermelho");
      //  tipo = t.equals("estrela 17");
      // tipo = t.equals("V8");
        menuIni.decrementaExt();
        int stock = menuIni.getStockExt();
        ConfigDetalhesExteriores d = new ConfigDetalhesExteriores(custo, t, l, m,  ref, this.id_configuraExt, tipo, stock);

        
        carro.adicionarConfigExt(d);
        this.setVisible(false);
        ConfiguraDetalhesInt s = new ConfiguraDetalhesInt(carro, username, menuIni,id_configura,id_configuraExt);
        s.setVisible(true);
    }//GEN-LAST:event_AdicionarButtonActionPerformed

    
        

        
        
        
                                                
                                     

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSpinnerPara;
    private javax.swing.JSpinner jSpinnerTecto;
    private javax.swing.JSpinner jSpinnerVidros;
    // End of variables declaration//GEN-END:variables
}


